# Generated by Django 3.0.6 on 2020-07-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200624_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='groups',
            field=models.ManyToManyField(to='app.GroupQuestionsModel'),
        ),
    ]
