# Generated by Django 3.0.6 on 2020-07-02 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_testmodel_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupInTestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.GroupQuestionsModel')),
            ],
        ),
    ]
