# Generated by Django 3.0.6 on 2020-07-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_groupintestmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='groups',
            field=models.ManyToManyField(blank=True, null=True, to='app.GroupQuestionsModel'),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='questions',
            field=models.ManyToManyField(blank=True, null=True, to='app.QuestionInTestModel'),
        ),
    ]
