# Generated by Django 3.0.6 on 2020-07-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200702_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='img',
            field=models.TextField(blank=True),
        ),
    ]
